[package]
name = "orx-parallel-wasm-allocator"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["rlib"]

[dependencies]
talc = "5.1.1"
spinning_top = "0.3"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

# Configure the shard count with WasmParallelAllocator's const generic.
