[package]
name = "orx-parallel-wasm-allocator"
version = "0.2.0"
edition = "2024"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
readme = "README.md"
description = "Allocator specialized for parallel computaitons in WASM"
license = "MIT OR Apache-2.0"
repository = "https://github.com/orxfun/orx-parallel-wasm-allocator/"
keywords = ["parallel", "concurrency", "web", "thread", "webassembly"]
categories = ["concurrency", "algorithms", "wasm", "web-programming"]

[lib]
crate-type = ["rlib"]

[dependencies]
talc = "5.1.1"
spinning_top = "0.3"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"
